services:
  - type: web
    runtime: static
    name: jintainokouzoutokinou-quiz
    repo: https://github.com/miiichiii/jintainokouzoutokinou
    branch: main
    buildCommand: "true"
    staticPublishPath: .
